### ISSUE TITLE
登陆不上 直接就报错

### ISSUE THREAD

**Issue by shizu2014** [Henryhaohao/Qimai_AppData#7]
Traceback (most recent call last):
  File "qimai_login.py", line 77, in <module>
    qimai_login()
  File "qimai_login.py", line 28, in qimai_login
    analysis = jsdata.call('get_analysis', url, '{}')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: m.sort is not a function

**Comment by eddilelau** [comment]
encrypt_20190716.js中602行注释掉
qimai_login.py 中注释掉analysis = json.loads(analysis).get('analysis')

**Comment by shizu2014** [comment]
localhost:Spiders shizu$ python3 qimai.py
{'code': 10602, 'msg': 'Access Error'}
老哥按照你给的登录成功了 但是获取榜单的时间提示权限错误 你遇到过这个问题吗

**Comment by hefy8655** [comment]
我也是这样子
{'code': 10602, 'msg': 'Access Error'}
是不是加密的方法改了？
